GET http://localhost:8080 HTTP/1.1
Content-Type: application/json

#####

GET http://localhost:8080/api/policies HTTP/1.1
Content-Type: application/json

#####

POST http://localhost:8080/api/policies HTTP/1.1
Content-Type: application/json

{
  "name": "Silver Auto Policy",
  "type": "Auto",
  "holder_first_name": "Freddy",
  "holder_last_name": "Kreuger",
  "holder_account_id": "666",
  "is_active": true,
  "has_active_claim": false,
  "effective_date": "2020-01-01",
  "termination_date": "2020-12-31"
}